In [1]:
import numpy as np
from datetime import date, timedelta

In [2]:
array = np.random.rand(3,3,3)
array

array([[[0.24917832, 0.31973897, 0.92624723],
        [0.92490117, 0.29498712, 0.09982071],
        [0.63963721, 0.07948442, 0.3841657 ]],

       [[0.41385816, 0.13905111, 0.13363389],
        [0.58494331, 0.88905431, 0.36973142],
        [0.47405966, 0.70281735, 0.49344562]],

       [[0.98300999, 0.41564724, 0.30671977],
        [0.19778452, 0.62659725, 0.46614905],
        [0.00171767, 0.48627133, 0.09793591]]])

In [3]:
array = np.diag(np.arange(4) + 1, k = -1)
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [4]:
array = np.tile(np.array([[0,1],[1,0]]), (4,4))
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
array = np.random.random((5,5))
array = (array - np.mean (array)) / (np.std (array))
array

array([[ 0.34886107, -1.56046355,  1.44200254,  0.9631333 ,  1.05456493],
       [-0.53854975, -0.97330509,  0.82907883, -1.16068155, -0.22170258],
       [-0.73495285,  0.66767314, -1.43207686,  0.39608835, -1.19058047],
       [ 0.43896352,  1.00839529,  0.90670436,  0.91953743, -0.95164939],
       [-1.01540771,  1.23003427, -0.67591999,  1.46244822, -1.21219545]])

In [8]:
array1 = np.random.randint(0,15,15)
array2 = np.random.randint(0,15,15)

np.intersect1d(array1, array2)

array([ 2,  3,  5,  8, 10, 12, 13])

In [9]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-08 2020-08-09 2020-08-10


In [11]:
array1 = np.random.rand(4,4)
array2 = np.random.rand(4,4)

equal = np.array_equal(array1,array2)
print(f'Array1:\n{array1}\n\n')
print(f'Array2:\n{array2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.69134687 0.08339277 0.05885499 0.01245029]
 [0.70563778 0.8690818  0.43508246 0.25539462]
 [0.36181309 0.91005404 0.04249711 0.21806641]
 [0.18399767 0.25359538 0.06281791 0.12548104]]


Array2:
[[0.86314114 0.01570386 0.17110015 0.31157789]
 [0.3496921  0.78494372 0.88802212 0.64102114]
 [0.34832847 0.297453   0.82502825 0.38612747]
 [0.30574973 0.62757422 0.08781351 0.24148974]]


Equality: False


In [12]:
array = np.random.rand(10)
array[array.argmax()] = 0
array

array([0.26780067, 0.5046749 , 0.1740557 , 0.        , 0.4918148 ,
       0.77478037, 0.27869765, 0.25791605, 0.44037697, 0.61504375])

In [13]:
array = np.ones((5, 5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
array = np.random.rand(5,5)
array_mean = array - array.mean(axis=1, keepdims=True)

array_mean

array([[ 0.50506692, -0.09488309, -0.21789187,  0.06153488, -0.25382684],
       [-0.0456072 ,  0.54674537, -0.05145891, -0.14284778, -0.30683148],
       [ 0.29022496, -0.29317696,  0.27909911, -0.55044393,  0.27429682],
       [-0.36833291,  0.39364126, -0.04059501,  0.27419885, -0.25891219],
       [ 0.38687407, -0.46389874, -0.42874008,  0.38249531,  0.12326944]])

In [17]:
array1 = np.ones(5)
array2 = np.random.randint(0, len(array1), 10)
array1 += np.bincount(array2, minlength = len(array1))
array1

array([3., 3., 4., 2., 3.])

In [19]:
array1 = np.random.randint(0,10,(4,4))
array2 = np.random.randint(0,10,(4,4))

np.einsum("ij,ji->i", array1, array2)

array([ 69, 128,  88,  49])

In [20]:
array = np.random.randint(0,10,20)
print(array)
max(set(array), key = list(array).count)

[7 7 2 4 6 3 6 7 2 8 7 9 7 5 3 4 5 2 6 5]


7

In [24]:
array = np.random.randint(0,10,30)
np.bincount(array).argmax()

9

In [26]:
array = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(array)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(array.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])